import './globals.css'
import { Metadata } from 'next'
import Navbar from '@/app/nav/Navbar'

export const metadata: Metadata = {
  title: 'Carsties Course',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className={'container mx-auto px-5 pt-10'}>{children}</main>
      </body>
    </html>
  )
}
